FROM python:3.11-slim
RUN apt-get update && apt-get install -y curl
WORKDIR /app
COPY src/valAPI /app/valAPI
RUN pip install --no-cache-dir fastapi uvicorn
EXPOSE 8000
CMD ["uvicorn", "valAPI.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]